[
	{"formatName":"Textfile","extensions":["txt"]},
	{"formatName":"Flash Actionscript","extensions":["as","mx"]},
	{"formatName":"Ada File","extensions":["ada","ads","adb"]},
	{"formatName":"Assembly language source file","extensions":["asm"]},
	{"formatName":"Active server pages script file","extensions":["asp"]},
	{"formatName":"AutoIt","extensions":["au3"]},
	{"formatName":"BaanC","extensions":["bc","cln"]},
	{"formatName":"Unix Script","extensions":["bash","sh","bsh","csh","bash_profile","profile"]},
	{"formatName":"Batch","extensions":["bat","cmd","nt"]},
	{"formatName":"C source","extensions":["c","lex"]},
	{"formatName":"Categorial Abstract Machine","extensions":["ml","mli","sml","thy"]},
	{"formatName":"CMake","extensions":["cmake"]},
	{"formatName":"Common Business Oriented Language","extensions":["cbd","cdc","cob"]},
	{"formatName":"CoffeeScript","extensions":["litcoffee"]},
	{"formatName":"C++ Source","extensions":["h","hpp","hxx","cpp","cxx","cc","ino"]},
	{"formatName":"C# source","extensions":["cs"]},
	{"formatName":"Cascade Style Sheet","extensions":["css"]},
	{"formatName":"D programming language","extensions":["d"]},
	{"formatName":"Diff","extensions":["diff","patch"]},
	{"formatName":"Fortran free form source","extensions":["f","for","f90","f95","f2k","f23"]},
	{"formatName":"Fortran fixed form source","extensions":["f77"]},
	{"formatName":"Haskell","extensions":["hs","lhs","las"]},
	{"formatName":"Hyper Text Markup Language","extensions":["html","htm","shtml","shtm","xhtml","xht","hta"]},
	{"formatName":"MS ini","extensions":["ini","inf","reg","url","wer"]},
	{"formatName":"Inno Setup","extensions":["iss"]},
	{"formatName":"Intel HEX binary","extensions":["hex"]},
	{"formatName":"Java Source","extensions":["java"]},
	{"formatName":"JavaScript","extensions":["js","jsm","jsx","ts","tsx"]},
	{"formatName":"JavaServer  Pages script","extensions":["jsp"]},
	{"formatName":"JSON","extensions":["json"]},
	{"formatName":"KiXtart","extensions":["kix"]},
	{"formatName":"List processing language","extensions":["lsp","lisp"]},
	{"formatName":"Lua source","extensions":["lua"]},
	{"formatName":"Makefile","extensions":["mak"]},
	{"formatName":"MATrix LABoratory","extensions":["m"]},
	{"formatName":"MSDOS Style/ASCII Art","extensions":["nfo"]},
	{"formatName":"Nullsoft Scriptable Install System script","extensions":["nsi","nsh"]},
	{"formatName":"Objective-C source","extensions":["mm"]},
	{"formatName":"Pascall source","extensions":["pas","pp","p","lpr"]},
	{"formatName":"Perl source","extensions":["pl","pm","plx"]},
	{"formatName":"PHP Hypertext Preprocessor","extensions":["php","php3","php4","php5","phps","phpt","phtml"]},
	{"formatName":"PostScript","extensions":["ps"]},
	{"formatName":"Windows PowerShell","extensions":["ps1","psm1"]},
	{"formatName":"Properties","extensions":["properties"]},
	{"formatName":"Python","extensions":["py","pyw"]},
	{"formatName":"R programming language","extensions":["r","s","splus"]},
	{"formatName":"Windows Resource","extensions":["rc"]},
	{"formatName":"Ruby file","extensions":["rb","rbw"]},
	{"formatName":"Scheme","extensions":["scm","smd","ss"]},
	{"formatName":"Structured Query language","extensions":["sql"]},
	{"formatName":"Motorola S-Record binary data","extensions":["mot","srec"]},
	{"formatName":"Tool Command Language","extensions":["tcl"]},
	{"formatName":"Tektronix extended HEX binary data","extensions":["tek"]},
	{"formatName":"Tex","extensions":["tex"]},
	{"formatName":"Visual Basic","extensions":["vb","vbs"]},
	{"formatName":"Verilog","extensions":["v","sv","vh","svh"]},
	{"formatName":"VHSIC Hardware Description Language","extensions":["ps"]},
	{"formatName":"eXtensible Markup Language","extensions":["xml","xaml","xsl","xslt","xsd","xul","kml","svg","mxml","xsml","wsdl","xlf","xliff","xbl","sxbl","sitemap","gml","gpx","plist"]},
	{"formatName":"YAML Ain't Markup Language","extensions":["yml","yaml"]}
]